spring:
  application:
    name: PhylacStoreServer
  datasource:
    url: jdbc:postgresql://localhost:5432/phylactery_db
    username: dirwul
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
