server:
  port: 9010

spring:
  application:
    name: Phylactery-Store-Server
  datasource:
    url: jdbc:postgresql://localhost:5432/phylactery_server
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

minio:
  endpoint: "http://localhost:9000"
  root:
    accessKey: ${MINIO_USER}
    secretKey: ${MINIO_PASS}