name: App Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: self-hosted

    steps:
      - name: Setup ngrok token
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
        run: mvn clean package

      - name: Deploy new jar with service restart
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          sudo -n systemctl stop phylac.service
          mv target/PhylacStoreServer-0.0.1-SNAPSHOT.jar /app/phylac/app.jar
          sudo -n systemctl start phylac.service
          sudo -n systemctl status phylac.service --no-pager
