name: App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package

      - name: Copy jar to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          source: target/PhylacStoreServer-0.0.1-SNAPSHOT.jar
          target: /app/phylac/tmp-app.jar

      - name: Deploy new jar with service restart
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl stop phylac.service
            mv /app/phylac/tmp-app.jar /app/phylac/app.jar
            sudo systemctl start phylac.service
            sudo systemctl status phylac.service --no-pager
