name: Phylactery Store CI/CD with maven
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, Linux ]

    steps:
      - name: Copy Github Secrets to .env file
        run: |
          sudo echo "${{ secrets.ENV_KEYS }}" > /app/phylactery.env

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: mvn clean package

      - name: Update .jar
        run: |
          sudo systemctl stop phylactery.service
          sudo mv target/phylactery-store.jar /app/phylactery-store.jar
          sudo systemctl start phylactery.service