name: Phylactery Store CI/CD with maven
on:
  push:
    branches: [ main ]

env:
  # secret
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  MINIO_USER: ${{ secrets.MINIO_USER }}
  MINIO_PASS: ${{ secrets.MINIO_PASS }}


jobs:
  deploy:
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: mvn clean package

      - name: Update .jar
        run: |
          sudo systemctl stop phylactery.service
          cp target/phylactery-store.jar /app/phylactery-store.jar
          sudo systemctl start phylactery.service
